# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last name')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('born', models.DateTimeField(db_index=True, verbose_name='born date')),
                ('died', models.DateTimeField(blank=True, db_index=True, help_text='leave empty if member is still alive', null=True, verbose_name='date of death')),
                ('children', models.ManyToManyField(related_name='_familymember_children_+', to='tree.FamilyMember')),
                ('parents', models.ManyToManyField(related_name='_familymember_parents_+', to='tree.FamilyMember')),
            ],
        ),
    ]
