# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='family_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='family name'),
        ),
    ]
