# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_familymember_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='born',
            field=models.DateField(db_index=True, verbose_name='born date'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_familymember_children_+', to='tree.FamilyMember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='died',
            field=models.DateField(blank=True, db_index=True, help_text='leave empty if member is still alive', null=True, verbose_name='date of death'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='_familymember_parents_+', to='tree.FamilyMember'),
        ),
    ]
