# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='member',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='children',
        ),
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
